ALTER TYPE "BackgroundJobType" ADD VALUE IF NOT EXISTS 'REGISTRATION_STARTED_NOTIFICATION';
ALTER TYPE "BackgroundJobType" ADD VALUE IF NOT EXISTS 'ROUND_STARTED_NOTIFICATION';
ALTER TYPE "BackgroundJobType" ADD VALUE IF NOT EXISTS 'SUBMISSION_CLOSED_NOTIFICATION';
